"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = BASE_DIR.parent.parent


env = environ.Env()
env.read_env(REPO_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    SECRET_KEY = env("DJANGO_SECRET_KEY", default="django-insecure-dev-only-change-me")
else:
    SECRET_KEY = env("DJANGO_SECRET_KEY")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "drf_spectacular",
    "anymail",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.headless",
    "accounts.apps.AccountsConfig",
    "api.apps.ApiConfig",
    "core",
    "django_filters",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media (utilise seulement en secours local quand S3/MinIO est injoignable en dev)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
BACKEND_BASE_URL = env("BACKEND_BASE_URL", default="http://127.0.0.1:8000")

S3_ENDPOINT_URL = env("S3_ENDPOINT_URL", default=None)
S3_ACCESS_KEY_ID = env("S3_ACCESS_KEY_ID", default=None)
S3_SECRET_ACCESS_KEY = env("S3_SECRET_ACCESS_KEY", default=None)
S3_BUCKET_NAME = env("S3_BUCKET_NAME", default=None)
PROFILE_PICTURE_S3_BUCKET_NAME = (
    env("PROFILE_PICTURE_S3_BUCKET_NAME", default=None) or S3_BUCKET_NAME
)
S3_REGION = env("S3_REGION", default="us-east-1")
S3_PRESIGNED_URL_EXPIRES_SECONDS = env.int(
    "S3_PRESIGNED_URL_EXPIRES_SECONDS",
    default=300,
)

DOCUMENT_MAX_UPLOAD_SIZE_BYTES = env.int(
    "DOCUMENT_MAX_UPLOAD_SIZE_BYTES",
    default=100 * 1024 * 1024,
)
DOCUMENT_ALLOWED_FILE_EXTENSIONS = set(env.list(
    "DOCUMENT_ALLOWED_FILE_EXTENSIONS",
    default={
        ".pdf", ".jpg", ".jpeg", ".png", ".webp", ".gif", ".tif", ".tiff",
        ".bmp", ".svg", ".heic", ".heif", ".dwg", ".dxf", ".ifc", ".rvt",
        ".skp", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".txt",
        ".csv",
    },
))
DOCUMENT_ALLOWED_MIME_TYPES = set(env.list(
    "DOCUMENT_ALLOWED_MIME_TYPES",
    default={
        "application/pdf",
        "image/jpeg",
        "image/png",
        "image/webp",
        "image/gif",
        "image/tiff",
        "image/bmp",
        "image/svg+xml",
        "image/heic",
        "image/heif",
        "application/acad",
        "application/x-acad",
        "application/autocad_dwg",
        "image/vnd.dwg",
        "application/dwg",
        "application/dxf",
        "image/vnd.dxf",
        "application/ifc",
        "application/x-step",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-excel",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "application/vnd.ms-powerpoint",
        "text/plain",
        "text/csv",
    },
))
DOCUMENT_FALLBACK_MIME_TYPES = set(env.list(
    "DOCUMENT_FALLBACK_MIME_TYPES",
    default={"application/octet-stream"},
))

PROFILE_PICTURE_MAX_UPLOAD_SIZE_BYTES = env.int(
    "PROFILE_PICTURE_MAX_UPLOAD_SIZE_BYTES",
    default=5 * 1024 * 1024,
)
PROFILE_PICTURE_ALLOWED_FILE_EXTENSIONS = set(env.list(
    "PROFILE_PICTURE_ALLOWED_FILE_EXTENSIONS",
    default={".jpg", ".jpeg", ".png", ".webp", ".gif"},
))
PROFILE_PICTURE_ALLOWED_MIME_TYPES = set(env.list(
    "PROFILE_PICTURE_ALLOWED_MIME_TYPES",
    default={"image/jpeg", "image/png", "image/webp", "image/gif"},
))

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="Project Gestion <no-reply@project-gestion.local>",
)
SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
DEFAULT_REPLY_TO_EMAIL = env("DEFAULT_REPLY_TO_EMAIL", default=None) or None

RESEND_API_KEY = env("RESEND_API_KEY", default="")
RESEND_INVITATION_TEMPLATE_ID = env("RESEND_INVITATION_TEMPLATE_ID", default="")
RESEND_PASSWORD_RESET_TEMPLATE_ID = env("RESEND_PASSWORD_RESET_TEMPLATE_ID", default="")
RESEND_EMAIL_VERIFICATION_TEMPLATE_ID = env(
    "RESEND_EMAIL_VERIFICATION_TEMPLATE_ID",
    default="",
)
RESEND_SIGNING_SECRET = env("RESEND_SIGNING_SECRET", default=None)

EMAIL_BACKEND = env("EMAIL_BACKEND", default="") or (
    "anymail.backends.resend.EmailBackend"
    if RESEND_API_KEY
    else "django.core.mail.backends.console.EmailBackend"
)

if EMAIL_BACKEND == "anymail.backends.resend.EmailBackend" and not RESEND_API_KEY:
    raise ImproperlyConfigured(
        "RESEND_API_KEY must be set when EMAIL_BACKEND uses Resend."
    )

ANYMAIL = {}
if RESEND_API_KEY:
    ANYMAIL["RESEND_API_KEY"] = RESEND_API_KEY
if RESEND_SIGNING_SECRET:
    ANYMAIL["RESEND_SIGNING_SECRET"] = RESEND_SIGNING_SECRET

FRONTEND_APP_URL = env("FRONTEND_APP_URL", default="") or env(
    "NEXT_PUBLIC_APP_URL",
    default="http://localhost:3000",
)
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        FRONTEND_APP_URL,
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
)
PASSWORD_RESET_CONFIRM_URL = env(
    "PASSWORD_RESET_CONFIRM_URL",
    default=f"{FRONTEND_APP_URL}/auth/reset-password",
)
EMAIL_VERIFICATION_URL = env(
    "EMAIL_VERIFICATION_URL",
    default=f"{FRONTEND_APP_URL}/auth/verify-email",
)
INVITATION_EXPIRES_DAYS = env.int("INVITATION_EXPIRES_DAYS", default=7)

# Le frontend appelle l'API depuis une autre origine avec `credentials: "include"`,
# donc le navigateur exige `Access-Control-Allow-Credentials` + une liste d'origines
# explicite (le wildcard `*` est interdit avec des cookies).
# `x-csrftoken` fait deja partie des en-tetes autorises par defaut.
CORS_ALLOW_CREDENTIALS = True

# Origines autorisees a poster un token CSRF. `AccountAdapter.is_safe_url` s'appuie
# aussi dessus pour valider le `callback_url` du flux OAuth headless.
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=CORS_ALLOWED_ORIGINS)


# Sessions Django (aucun token n'est expose au JavaScript du frontend)
# https://docs.djangoproject.com/en/6.0/ref/settings/#sessions

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
# "Lax" suffit tant que le frontend et l'API partagent le meme site (meme domaine
# enregistrable, le port n'entre pas en compte). Pour un deploiement reellement
# cross-site il faut "None" + cookies `Secure`.
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", default="Lax")
SESSION_COOKIE_DOMAIN = env("SESSION_COOKIE_DOMAIN", default=None) or None
SESSION_COOKIE_AGE = env.int("SESSION_COOKIE_AGE", default=60 * 60 * 24 * 14)
# Prolonge la session a chaque requete authentifiee (expiration glissante).
SESSION_SAVE_EVERY_REQUEST = True

# Le frontend doit pouvoir lire le cookie CSRF pour renvoyer l'en-tete `X-CSRFToken`,
# il ne peut donc pas etre HttpOnly (c'est le fonctionnement nominal de Django).
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SAMESITE = env("CSRF_COOKIE_SAMESITE", default=SESSION_COOKIE_SAMESITE)
CSRF_COOKIE_DOMAIN = env("CSRF_COOKIE_DOMAIN", default=None) or None

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "api.exceptions.exception_handler",
    # `SessionAuthentication` lit le cookie de session Django et applique la
    # verification CSRF sur les requetes non idempotentes (clients navigateur).
    # `XSessionTokenAuthentication` est l'integration DRF officielle d'allauth pour
    # le client "app" (mobile), qui transporte le meme session key via l'en-tete
    # `X-Session-Token` au lieu d'un cookie.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.SessionAuthentication",
        "allauth.headless.contrib.rest_framework.authentication.XSessionTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardPagination",
    "PAGE_SIZE": 50,
    # `SearchFilter` is a no-op unless a view declares `search_fields`, so it is safe
    # to default everywhere. `OrderingFilter`/`StableOrderingFilter` is NOT included
    # here: with no `ordering_fields` declared on the view, DRF falls back to allowing
    # ordering by *any* serializer field, which would silently grant new (and
    # potentially crash-prone) sorting capability to every list view that doesn't
    # opt in today. It stays an explicit, per-view opt-in alongside `ordering_fields`.
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    # Les flux d'authentification sont limites par allauth lui-meme
    # (`ACCOUNT_RATE_LIMITS`), ce throttle ne couvre que les vues du projet.
    "DEFAULT_THROTTLE_RATES": {
        "profile_picture": env("THROTTLE_PROFILE_PICTURE_RATE", default="10/hour"),
    },
}


# django-allauth
# https://docs.allauth.org/en/latest/account/configuration.html

ACCOUNT_ADAPTER = "accounts.adapters.AccountAdapter"
# Le username n'est pas demande a l'inscription : allauth le derive de l'email
# via `DefaultAccountAdapter.generate_unique_username`.
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]
ACCOUNT_SIGNUP_FORM_CLASS = "accounts.forms.SignupExtraFieldsForm"
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_PREVENT_ENUMERATION = True
ACCOUNT_RATE_LIMITS = {
    "login": env("THROTTLE_LOGIN_RATE", default="30/m/ip"),
    "login_failed": env("THROTTLE_LOGIN_FAILED_RATE", default="10/m/ip,5/300s/key"),
    "signup": env("THROTTLE_SIGNUP_RATE", default="20/m/ip"),
    "reset_password": env("THROTTLE_PASSWORD_RESET_RATE", default="20/m/ip,5/m/key"),
    "reset_password_from_key": env(
        "THROTTLE_PASSWORD_RESET_CONFIRM_RATE",
        default="20/m/ip",
    ),
    "change_password": env("THROTTLE_PASSWORD_CHANGE_RATE", default="5/m/user"),
    "confirm_email": env("THROTTLE_EMAIL_RESEND_RATE", default="1/180s/key"),
}

SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
GOOGLE_OAUTH_CLIENT_ID = env("GOOGLE_OAUTH_CLIENT_ID", default="")
GOOGLE_OAUTH_CLIENT_SECRET = env("GOOGLE_OAUTH_CLIENT_SECRET", default="")

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "EMAIL_AUTHENTICATION": True,
        "VERIFIED_EMAIL": True,
        "OAUTH_PKCE_ENABLED": True,
    }
}

# Credentials via settings plutot que via le modele `SocialApp` en base : le secret
# reste dans l'environnement et aucune donnee a saisir dans l'admin.
if GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS["google"]["APPS"] = [
        {
            "client_id": GOOGLE_OAUTH_CLIENT_ID,
            "secret": GOOGLE_OAUTH_CLIENT_SECRET,
            "key": "",
        }
    ]


# django-allauth headless
# https://docs.allauth.org/en/latest/headless/configuration.html

# Aucune vue HTML d'allauth n'est exposee : le projet ne sert que l'API headless.
HEADLESS_ONLY = True
# "browser" -> web (cookie de session + CSRF), "app" -> mobile (X-Session-Token).
HEADLESS_CLIENTS = ("browser", "app")
HEADLESS_SERVE_SPECIFICATION = env.bool("HEADLESS_SERVE_SPECIFICATION", default=DEBUG)
# URLs du frontend inserees dans les emails envoyes par allauth.
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{EMAIL_VERIFICATION_URL.rstrip('/')}?key={{key}}",
    "account_reset_password": f"{FRONTEND_APP_URL.rstrip('/')}/auth/forgot-password",
    "account_reset_password_from_key": (
        f"{PASSWORD_RESET_CONFIRM_URL.rstrip('/')}?key={{key}}"
    ),
    "account_signup": f"{FRONTEND_APP_URL.rstrip('/')}/auth/register",
    "socialaccount_login_error": f"{FRONTEND_APP_URL.rstrip('/')}/auth/login",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Project Gestion API",
    "DESCRIPTION": (
        "API de gestion de projets. L'authentification est assuree par "
        "django-allauth headless sous /_allauth/ (sessions Django)."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    #"POSTPROCESSING_HOOKS": [
    #    "api.schema.add_error_responses",
    #],
}
