"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = BASE_DIR.parent.parent


def load_env_file(path):
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()

        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_env_file(REPO_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes", "on"}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-change-me"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "drf_spectacular",
    "accounts",
    "api",
    "core",
    "django_filters",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

S3_ENDPOINT_URL = os.environ.get("S3_ENDPOINT_URL")
S3_ACCESS_KEY_ID = os.environ.get("S3_ACCESS_KEY_ID")
S3_SECRET_ACCESS_KEY = os.environ.get("S3_SECRET_ACCESS_KEY")
S3_BUCKET_NAME = os.environ.get("S3_BUCKET_NAME")
PROFILE_PICTURE_S3_BUCKET_NAME = os.environ.get(
    "PROFILE_PICTURE_S3_BUCKET_NAME",
    S3_BUCKET_NAME,
)
S3_REGION = os.environ.get("S3_REGION", "us-east-1")
S3_PRESIGNED_URL_EXPIRES_SECONDS = int(
    os.environ.get("S3_PRESIGNED_URL_EXPIRES_SECONDS", "300")
)

DOCUMENT_MAX_UPLOAD_SIZE_BYTES = int(
    os.environ.get("DOCUMENT_MAX_UPLOAD_SIZE_BYTES", str(100 * 1024 * 1024))
)
DOCUMENT_ALLOWED_FILE_EXTENSIONS = {
    extension.strip().lower()
    for extension in os.environ.get(
        "DOCUMENT_ALLOWED_FILE_EXTENSIONS",
        ".pdf,.jpg,.jpeg,.png,.webp,.gif,.tif,.tiff,.bmp,.svg,.heic,.heif,"
        ".dwg,.dxf,.ifc,.rvt,.skp,"
        ".doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv",
    ).split(",")
    if extension.strip()
}
DOCUMENT_ALLOWED_MIME_TYPES = {
    mime_type.strip().lower()
    for mime_type in os.environ.get(
        "DOCUMENT_ALLOWED_MIME_TYPES",
        "application/pdf,"
        "image/jpeg,image/png,image/webp,image/gif,image/tiff,image/bmp,"
        "image/svg+xml,image/heic,image/heif,"
        "application/acad,application/x-acad,application/autocad_dwg,"
        "image/vnd.dwg,application/dwg,"
        "application/dxf,image/vnd.dxf,"
        "application/ifc,application/x-step,"
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document,"
        "application/msword,"
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,"
        "application/vnd.ms-excel,"
        "application/vnd.openxmlformats-officedocument.presentationml.presentation,"
        "application/vnd.ms-powerpoint,"
        "text/plain,text/csv",
    ).split(",")
    if mime_type.strip()
}
DOCUMENT_FALLBACK_MIME_TYPES = {
    mime_type.strip().lower()
    for mime_type in os.environ.get(
        "DOCUMENT_FALLBACK_MIME_TYPES",
        "application/octet-stream",
    ).split(",")
    if mime_type.strip()
}

PROFILE_PICTURE_MAX_UPLOAD_SIZE_BYTES = int(
    os.environ.get("PROFILE_PICTURE_MAX_UPLOAD_SIZE_BYTES", str(5 * 1024 * 1024))
)
PROFILE_PICTURE_ALLOWED_FILE_EXTENSIONS = {
    extension.strip().lower()
    for extension in os.environ.get(
        "PROFILE_PICTURE_ALLOWED_FILE_EXTENSIONS",
        ".jpg,.jpeg,.png,.webp,.gif",
    ).split(",")
    if extension.strip()
}
PROFILE_PICTURE_ALLOWED_MIME_TYPES = {
    mime_type.strip().lower()
    for mime_type in os.environ.get(
        "PROFILE_PICTURE_ALLOWED_MIME_TYPES",
        "image/jpeg,image/png,image/webp,image/gif",
    ).split(",")
    if mime_type.strip()
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ]
}

SPECTACULAR_SETTINGS = {
    "TITLE": "API d'Authentification JWT",
    "DESCRIPTION": "API avec authentification JWT utilisant DRF + Spectacular",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    #"POSTPROCESSING_HOOKS": [
    #    "api.schema.add_error_responses",
    #],
}
