"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = BASE_DIR.parent.parent


env = environ.Env()
env.read_env(REPO_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    SECRET_KEY = env("DJANGO_SECRET_KEY", default="django-insecure-dev-only-change-me")
else:
    SECRET_KEY = env("DJANGO_SECRET_KEY")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "anymail",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "accounts.apps.AccountsConfig",
    "api.apps.ApiConfig",
    "core",
    "django_filters",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

S3_ENDPOINT_URL = env("S3_ENDPOINT_URL", default=None)
S3_ACCESS_KEY_ID = env("S3_ACCESS_KEY_ID", default=None)
S3_SECRET_ACCESS_KEY = env("S3_SECRET_ACCESS_KEY", default=None)
S3_BUCKET_NAME = env("S3_BUCKET_NAME", default=None)
PROFILE_PICTURE_S3_BUCKET_NAME = (
    env("PROFILE_PICTURE_S3_BUCKET_NAME", default=None) or S3_BUCKET_NAME
)
S3_REGION = env("S3_REGION", default="us-east-1")
S3_PRESIGNED_URL_EXPIRES_SECONDS = env.int(
    "S3_PRESIGNED_URL_EXPIRES_SECONDS",
    default=300,
)

DOCUMENT_MAX_UPLOAD_SIZE_BYTES = env.int(
    "DOCUMENT_MAX_UPLOAD_SIZE_BYTES",
    default=100 * 1024 * 1024,
)
DOCUMENT_ALLOWED_FILE_EXTENSIONS = set(env.list(
    "DOCUMENT_ALLOWED_FILE_EXTENSIONS",
    default={
        ".pdf", ".jpg", ".jpeg", ".png", ".webp", ".gif", ".tif", ".tiff",
        ".bmp", ".svg", ".heic", ".heif", ".dwg", ".dxf", ".ifc", ".rvt",
        ".skp", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".txt",
        ".csv",
    },
))
DOCUMENT_ALLOWED_MIME_TYPES = set(env.list(
    "DOCUMENT_ALLOWED_MIME_TYPES",
    default={
        "application/pdf",
        "image/jpeg",
        "image/png",
        "image/webp",
        "image/gif",
        "image/tiff",
        "image/bmp",
        "image/svg+xml",
        "image/heic",
        "image/heif",
        "application/acad",
        "application/x-acad",
        "application/autocad_dwg",
        "image/vnd.dwg",
        "application/dwg",
        "application/dxf",
        "image/vnd.dxf",
        "application/ifc",
        "application/x-step",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-excel",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "application/vnd.ms-powerpoint",
        "text/plain",
        "text/csv",
    },
))
DOCUMENT_FALLBACK_MIME_TYPES = set(env.list(
    "DOCUMENT_FALLBACK_MIME_TYPES",
    default={"application/octet-stream"},
))

PROFILE_PICTURE_MAX_UPLOAD_SIZE_BYTES = env.int(
    "PROFILE_PICTURE_MAX_UPLOAD_SIZE_BYTES",
    default=5 * 1024 * 1024,
)
PROFILE_PICTURE_ALLOWED_FILE_EXTENSIONS = set(env.list(
    "PROFILE_PICTURE_ALLOWED_FILE_EXTENSIONS",
    default={".jpg", ".jpeg", ".png", ".webp", ".gif"},
))
PROFILE_PICTURE_ALLOWED_MIME_TYPES = set(env.list(
    "PROFILE_PICTURE_ALLOWED_MIME_TYPES",
    default={"image/jpeg", "image/png", "image/webp", "image/gif"},
))

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="Project Gestion <no-reply@project-gestion.local>",
)
SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
DEFAULT_REPLY_TO_EMAIL = env("DEFAULT_REPLY_TO_EMAIL", default=None) or None

RESEND_API_KEY = env("RESEND_API_KEY", default="")
RESEND_INVITATION_TEMPLATE_ID = env("RESEND_INVITATION_TEMPLATE_ID", default="")
RESEND_PASSWORD_RESET_TEMPLATE_ID = env("RESEND_PASSWORD_RESET_TEMPLATE_ID", default="")
RESEND_EMAIL_VERIFICATION_TEMPLATE_ID = env(
    "RESEND_EMAIL_VERIFICATION_TEMPLATE_ID",
    default="",
)
RESEND_SIGNING_SECRET = env("RESEND_SIGNING_SECRET", default=None)

EMAIL_BACKEND = env("EMAIL_BACKEND", default="") or (
    "anymail.backends.resend.EmailBackend"
    if RESEND_API_KEY
    else "django.core.mail.backends.console.EmailBackend"
)

if EMAIL_BACKEND == "anymail.backends.resend.EmailBackend" and not RESEND_API_KEY:
    raise ImproperlyConfigured(
        "RESEND_API_KEY must be set when EMAIL_BACKEND uses Resend."
    )

ANYMAIL = {}
if RESEND_API_KEY:
    ANYMAIL["RESEND_API_KEY"] = RESEND_API_KEY
if RESEND_SIGNING_SECRET:
    ANYMAIL["RESEND_SIGNING_SECRET"] = RESEND_SIGNING_SECRET

FRONTEND_APP_URL = env("FRONTEND_APP_URL", default="") or env(
    "NEXT_PUBLIC_APP_URL",
    default="http://localhost:3000",
)
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        FRONTEND_APP_URL,
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
)
PASSWORD_RESET_CONFIRM_URL = env(
    "PASSWORD_RESET_CONFIRM_URL",
    default=f"{FRONTEND_APP_URL}/auth/reset-password",
)
EMAIL_VERIFICATION_URL = env(
    "EMAIL_VERIFICATION_URL",
    default=f"{FRONTEND_APP_URL}/auth/verify-email",
)
GOOGLE_OAUTH_CALLBACK_URL = env(
    "GOOGLE_OAUTH_CALLBACK_URL",
    default=f"{FRONTEND_APP_URL}/auth/google/callback",
)
INVITATION_EXPIRES_DAYS = env.int("INVITATION_EXPIRES_DAYS", default=7)

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "login": env("THROTTLE_LOGIN_RATE", default="5/min"),
        "register": env("THROTTLE_REGISTER_RATE", default="5/hour"),
        "password_reset": env("THROTTLE_PASSWORD_RESET_RATE", default="3/hour"),
        "password_reset_confirm": env(
            "THROTTLE_PASSWORD_RESET_CONFIRM_RATE",
            default="10/hour",
        ),
        "password_change": env("THROTTLE_PASSWORD_CHANGE_RATE", default="10/hour"),
        "email_verify": env("THROTTLE_EMAIL_VERIFY_RATE", default="10/hour"),
        "email_resend": env("THROTTLE_EMAIL_RESEND_RATE", default="3/hour"),
        "google_login": env("THROTTLE_GOOGLE_LOGIN_RATE", default="10/min"),
        "profile_picture": env("THROTTLE_PROFILE_PICTURE_RATE", default="10/hour"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env.int("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", default=15),
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env.int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", default=7),
    ),
    "ROTATE_REFRESH_TOKENS": env.bool("JWT_ROTATE_REFRESH_TOKENS", default=False),
    "BLACKLIST_AFTER_ROTATION": env.bool("JWT_BLACKLIST_AFTER_ROTATION", default=True),
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "TOKEN_MODEL": None,
    "USER_DETAILS_SERIALIZER": "accounts.serializers.UserSerializer",
}

SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
ACCOUNT_ADAPTER = "accounts.adapters.AccountAdapter"
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "EMAIL_AUTHENTICATION": True,
        "VERIFIED_EMAIL": True,
        "OAUTH_PKCE_ENABLED": True,
    }
}

SPECTACULAR_SETTINGS = {
    "TITLE": "API d'Authentification JWT",
    "DESCRIPTION": "API avec authentification JWT utilisant DRF + Spectacular",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    #"POSTPROCESSING_HOOKS": [
    #    "api.schema.add_error_responses",
    #],
}
