# Generated by Django 6.0.6 on 2026-06-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_created_at_alter_profile_deleted_at'),
        ('api', '0044_alter_task_status_priority_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.project'),
        ),
    ]
