# Generated by Django 6.0.6 on 2026-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_project_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialentry',
            name='type',
            field=models.CharField(choices=[('expense', 'financial.types.expense'), ('invoice', 'financial.types.invoice'), ('refund', 'financial.types.refund'), ('payment', 'financial.types.payment')], max_length=50),
        ),
    ]
