# Generated by Django 6.0.6 on 2026-06-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seed_task_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('provider', models.CharField(default='resend', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'email_delivery.status.pending'), ('sent', 'email_delivery.status.sent'), ('delivered', 'email_delivery.status.delivered'), ('failed', 'email_delivery.status.failed'), ('bounced', 'email_delivery.status.bounced'), ('deferred', 'email_delivery.status.deferred'), ('complained', 'email_delivery.status.complained'), ('opened', 'email_delivery.status.opened'), ('clicked', 'email_delivery.status.clicked')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('complained_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.invitation')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
