# Generated by Django 6.0.6 on 2026-06-12 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_emaildelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('deleted_at__isnull', True)), fields=('project', 'email'), name='unique_active_pending_invitation'),
        ),
    ]
