# Generated by Django 6.0.6 on 2026-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_seed_expense_request_restore_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='time_entries', to='api.document'),
        ),
    ]
