# Generated by Django 6.0.6 on 2026-06-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_document_created_at_alter_document_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high')], db_index=True, default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('in_progress', 'in_progress'), ('done', 'done')], db_index=True, default='todo', max_length=50),
        ),
    ]
