# Generated by Django 6.0.6 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_task_status_priority_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
