# Generated by Django 6.0.6 on 2026-06-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_seed_member_rate_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOwnerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rate', to='api.project')),
            ],
        ),
    ]
