# Generated by Django 6.0.6 on 2026-07-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_timeentry_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='api.document'),
        ),
    ]
