# Generated by Django 6.0.6 on 2026-07-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_task_documents'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_active_document_name_per_folder',
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_active_root_document_name',
        ),
    ]
