# Generated by Django 6.0.6 on 2026-07-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_timeentry_start_date_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialentry',
            name='category',
        ),
    ]
