# Generated by Django 6.0.6 on 2026-08-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_seed_time_entry_view_others_detail_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
